493 quick action to opentextual editor to the side
KaotoIO/vscode-kaoto pull request #628
Opened 2024-08-08 12:53 UTC by apupier

based on https://github.com/KaotoIO/vscode-kaoto/pull/627

![quickactionToShowSource](https://github.com/user-attachments/assets/4fa782f7-d275-4eef-9c8d-47aa3bd6033e)

2024-08-12 12:34 UTC, djelinek requested changes

2024-08-12 12:34 UTC, djelinek commented on it-tests/OpenTextualEditorCommand.test.ts
> +describe.only('Open Textual editor to the side', function () {
remove `only`

2024-08-12 14:06 UTC, apupier commented
tests are failing because the quick actions are not appearing at all... even after 20 seconds... none of them... investigating

2024-08-12 14:30 UTC, apupier commented
not sure if related, stack found in shared out put log:

```
2024-08-12 12:52:57.765 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat '/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/extensions.json.vsctmp'
    at h.create (/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:54:19262)
    at f (/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:54:19372)
    at P.hb (/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:59:36571)
    at P.stat (/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:59:28919)
    at async s.stat (/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:59:14907)
    at async V.vb (/home/runner/work/vscode-kaoto/vscode-kaoto/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcess/sharedProcessMain.js:105:119283)
 ```

2024-08-14 15:51 UTC, djelinek approved these changes

2024-08-16 07:04 UTC, merged